cricket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('backend/', include('cricketmain.urls'))
]

cricketmain/urls.py
from django.urls import path
from cricketmain.views import *

urlpatterns = [
    path('teams/', TeamView.as_view(), name='teams'),
    path('team/<int:team_id>/', TeamDetailView.as_view(), name='teamdetail'),
    path('match_fixture/', MatchFixture.as_view(), name='matchfixture'),
]

frontend/urls.py
from django.urls import path
from frontend.views import *
app_name = 'frontend'
urlpatterns = [
    path('', teamPage, name='teamspage'),
    path('<int:team_id>/', teamDetailPage, name='detailpage'),
    path('match_fixture/', matchFixtureView, name='match_fixture'),
]

cricketmain/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    name = models.TextField(max_length = 40)
    logo_uri = models.URLField()
    club_state = models.TextField(max_length = 40)

    class Meta:
        db_table = 'team'

class Player(models.Model):
    first_name = models.TextField(max_length = 40)
    last_name = models.TextField(max_length = 40)
    image_uri = models.URLField(max_length = 500)
    jersey_number = models.IntegerField()
    country = models.TextField(max_length = 40)
    history = models.TextField(max_length = 500)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    class Meta:
        db_table = 'player'

class Match(models.Model):
    teamone = models.ForeignKey(Team, related_name='teamone', on_delete=models.CASCADE)
    teamtwo = models.ForeignKey(Team, related_name='teamtwo', on_delete=models.CASCADE)
    winner = models.ForeignKey(Team, related_name='winner', on_delete=models.CASCADE)

    class Meta:
        db_table = 'match'

class Point(models.Model):
    points = models.IntegerField(default = 0)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    class Meta:
        db_table = 'point'

frontend/models.py
from django.db import models

# Create your models here.

cricketmain/views.py
import random
import itertools
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import *
from .serializers import *

# Create your views here.
class TeamView(APIView):
    def get(self, request, format = None):
        teams = Team.objects.all()
        serializer = TeamSerializer(teams, many = True)
        return Response(serializer.data)

class TeamDetailView(APIView):
    def get(self, request, team_id, format = None):
        player_data = []
        response = {}
        players = Player.objects.select_related('team').filter(team__id = team_id)
        for player in players:
            team_name = player.team.name
            player_data.append({'first_name': player.first_name, 'last_name': player.last_name,
            'image_uri': player.image_uri})
        response['players'] = player_data
        response['team_name'] = team_name
        serializer = TeamDetailSerializer(response)
        return Response(serializer.data)

class MatchFixture(APIView):
    def get(self, request, format = None):
        teams = Team.objects.all()
        pairs = list(itertools.combinations(teams, 2))
        random.shuffle(pairs)
        result = []
        count = 0
        points_dict = {}
        for team_name in teams:
            points_dict[team_name.name] = 0
        
        for i in pairs:
            temp = {}
            count += 1
            temp['matchnumber'] = count
            temp['teamone'] = i[0].name
            temp['teamtwo'] = i[1].name
            temp['winner'] = random.choice([temp['teamone'],temp['teamtwo']])
            points_dict[temp['winner']] += 5
            result.append(temp)
        sort_points = sorted(points_dict.items(), key=lambda x: x[1], reverse=True)
        rank = 1
        sort_points_out = []
        for i in sort_points:
            out_points = {}
            out_points['rank'] = rank
            out_points['team_name'] = i[0]
            out_points['points'] = i[1]
            rank += 1
            sort_points_out.append(out_points)

        serializer = MatchFixtureSerializer(result, many = True)
        response_api = {'matches':serializer.data, 'points':sort_points_out}
        return Response(response_api)

frontend/views.py
from django.shortcuts import render
import requests
import json


# Create your views here.
def teamPage(request):
    url = requests.get('http://127.0.0.1:8000/backend/teams/', None)
    return render(request, 'cricketmain/teams.html', {'teams' : json.loads(url.text)})

def teamDetailPage(request, team_id):
    url = requests.get('http://127.0.0.1:8000/backend/team/{team_id}/'.format(team_id=team_id), None)
    res = json.loads(url.text)
    return render(request, 'cricketmain/teamdetail.html',{'teamdetail': res['players'], 'team_name': res['team_name']})

def matchFixtureView(request):
    url = requests.get('http://127.0.0.1:8000/backend/match_fixture/', None)
    res = json.loads(url.text)
    return render(request, 'cricketmain/match_fixture.html',{'match_fixture': res['matches'],'points':res['points']})

frontend/templates/cricketmain/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

frontend/templates/cricketmain/match_fixture.html
{% extends "cricketmain/base.html" %}
{% load static %}
{% block page_content %}
<div style="text-align: center;">
    <h2> Match Fixtures</h2>
</div>
<div class="container table-responsive">
    <table class="table">
        <tr>
            <th style="width: 33%;">Match</th>
            <th style="width: 33%;">Pair</th>
            <th style="width: 33%;">Winner</th>
        </tr>
        {% for row in match_fixture %}
        <tr>
            <td>{{ row.matchnumber }}</td>
            <td>{{ row.teamone }} vs {{ row.teamtwo }}</td>
            <td>{{ row.winner }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

<div style="text-align: center;">
    <h2>Points Table</h2>
</div>
<div class="container table-responsive">
    <table class="table">
        <tr>
            <th style="width: 33%;">Rank</th>
            <th style="width: 33%;">Team Name</th>
            <th style="width: 33%;">Points</th>
        </tr>
        {% for row in points %}
        <tr>
            <td>{{ row.rank }}</td>
            <td>{{ row.team_name }}</td>
            <td>{{ row.points }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

frontend/templates/cricketmain/teamdetail.html
{% extends "cricketmain/base.html" %}
{% load static %}
{% block page_content %}
<div style="text-align: center;">
    <h4>{{ team_name }}</h4>
</div>
<div class="row">
    {% for data in teamdetail %}
    <div class="col-md-4">
        <div class="card mb-3">
            <img class="card-img-top" src={{data.image_uri}} height="300px">
            <div class="card-body">
                <h5 class="card-title">{{ data.first_name}} {{data.last_name}}</h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
    

frontend/templates/cricketmain/teams.html
<!DOCTYPE html>
{% extends "cricketmain/base.html" %}
{% load static %}
{% block page_content %}
<h1 style="text-align: center;">Cricket Application</h1>
    <div class="row">
        {% for team in teams %}
            <div class="col-md-3">
                <div class="card mb-3">
                    <img class="card-img-top" src={{team.logo_uri}} height="300px">
                    <div class="card-body">
                        <h5 class="card-title">{{ team.name }}</h5>
                        <!-- <p class="card-text">{{ team.club_state }}</p> -->
                        <a href="{% url 'frontend:detailpage' team.id %}"
                            class="btn btn-primary">
                                Read More
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div style="text-align: center;">
        <a href="{% url 'frontend:match_fixture' %}"
                            class="btn btn-primary">
                                Match Fixtures
                        </a>
    </div>
{% endblock %}